[allowlist]
paths = [
    '''gitleaks.toml''',
    '''(.*?)(jpg|gif|doc|pdf|bin)$''',
    '''(go.mod|go.sum)$'''
]

# Generic API Token
[[rules]]
id = "generic-api-key"
description = "Generic API Key"
regex = '''(?i)(api_key|apikey|secret|token)["'\s]*[:=>\s]+["'\s]*([\w\-+=]{32,})["'\s]*'''
secretGroup = 2

# Django Secret Key
[[rules]]
id = "django-secret-key"
description = "Django Secret Key"
regex = '''(?i)(SECRET_KEY|DJANGO_SECRET_KEY)["'\s]*[:=>\s]+["'\s]*([^"'\s]{8,})["'\s]*'''
secretGroup = 2

# Database URL
[[rules]]
id = "database-url"
description = "Database Connection String"
regex = '''(?i)(DATABASE_URL|DB_CONNECTION|POSTGRES_URL)["'\s]*[:=>\s]+["'\s]*([\w\-+=/@:]{8,})["'\s]*'''
secretGroup = 2

# Angular Environment Variables
[[rules]]
id = "angular-env-key"
description = "Angular Environment Key"
regex = '''(?i)(apiKey|authDomain|projectId|storageBucket|messagingSenderId|appId)["'\s]*[:=>\s]+["'\s]*([^"'\s]{8,})["'\s]*'''
secretGroup = 2 