name: Start Tox(Backend)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U test_user"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Wait for Database to be Ready
        run: |
          until pg_isready -h localhost -p 5432 -U test_user; do
            echo "Waiting for database to be ready..."
            sleep 5
          done

      - name: Export Environment Variables
        run: |
          echo "TEST_DATABASE_URL=postgres://test_user:test_password@localhost:5432/test_db" >> $GITHUB_ENV
          echo "IS_TEST=True" >> $GITHUB_ENV

      - name: Run Tox in `edufinder` Directory
        working-directory: ./edufinder
        run: |
          export TEST_DATABASE_URL=$TEST_DATABASE_URL
          export IS_TEST=$IS_TEST
          tox
        env:
          TEST_DATABASE_URL: ${{ env.TEST_DATABASE_URL }}
          IS_TEST: ${{ env.IS_TEST }}
